# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - master

stages:
  - stage: __default
    jobs:
      - job: Job
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "18"
            displayName: Install Node.js

          - task: CmdLine@2
            displayName: npm ci
            inputs:
              script: npm ci

          - task: CmdLine@2
            displayName: Install Playwright browsers
            inputs:
              script: npx playwright install --with-deps

          - task: CmdLine@2
            displayName: Run Playwright tests
            env:
              CI: "true"
            inputs:
              script: npx playwright test --project=ci

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: 'playwright-report'
              artifact: 'Report'
              publishLocation: 'pipeline'
            condition: 'always()'

          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '**/e2e-*.xml'
            condition: 'always()'
